# Site settings
title: Joshua Copeland
twitter_username: ogprogrammer
name: Josh Copeland

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.ogprogrammer.com/
 - title: GitHub
   url: https://github.com/ogprogrammer
# - title: StackOverflow
#   url: https://stackoverflow.com/users/3512214/ogprogrammer
# - title: DZone
#   url: https://dzone.com/users/3248538/ogprogrammer.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/ogprogrammer/

#Any buzzword skills you want to include
skills:
 - Web & Native Development
 - PHP
 - Symfony
 - Laravel
 - Behat
 - BDD/TDD
 - PHPUnit
 - ActiveMQ
 - RabbitMQ
 - SQS
 - Memcached
 - Redis
 - Elasticache
 - MySQL
 - RDS
 - MongoDB
 - Phaser
 - HTML5
 - ES6
 - Jenkins
 - Docker
 - Terraform
 - Bash
 - Linux/Mac/Win
 - Android/iOS
 - SQL
 - I18N
 - AWS/GCP
 - Groovy
 - Java
 - REST
 - Tech Architecture
 - Marketing
 - Gaming
 - Real Estate
 - Printers
 - Embeded
 - Swift
 - Python
 - Objective-C
 - C/C++
 - C#/VB .NET
 - Smart Contracts
 - Solidity
 - Blockchain

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://www.ogprogrammer.com/feed/

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: 2018
   employer: VehicleHistory.com
   description: Scouting and hiring five of devs for frontend, architect, and full stack roles. <br />Established agile methodologies & implemented Jira to track projects. <br />Lead architecture design of a micro-service based architecture. Using Jenkins+Docker+Terraform with AWS/ECS stacks. <br />Setup Jenkins for Automated Testing & Deployments of the various PHP services.
 - title: CTO
   start: 2016
   end: 2017
   employer: EngagedNation.com
   description: Taught a team of five how to use Git to version control websites and dependencies via composer & npm. <br />Screened and worked with local vendors to assist with large scale enterprise integrations in the Gaming industry.
 - title: Software Architect <br /><br />Lead Developer <br /><br />PHP Developer
   start: 2012
   end: 2017
   employer: The Selling Source
   description: Worked my way through the ranks from PHP Dev to Architect over my tenure there. <br />Quickly learned the complex systems written in various languages like PHP, Java, and Ruby. <br />Built tools & systems to integrate with partners using APIs, XSLT, SOAP, XML, and JSON. <br />Worked with large teams both in and out of the office on various projects to complete business initiatives.
 - title: Software Developer
   start: 2010
   end: 2012
   employer: Star Micronics
   description: Created SDK packages for Star's point of sale printers using multiple interfaces and languages such as C#, VB.NET, C++, Java, & Python. <br />Prototyped one off projects for desktop and mobile (iOS & Andriod) using various interfaces such as WiFi, Bluetooth, LAN, Serial, Parallel, and USB stacks. <br />Worked with large decentralized team throughout the US, UK, Japan, and South America.
 - title: Programmer
   start: 2010
   end: 2010
   employer: ReelTV
   description: ➢ Quickly absorded most of the linux, mysql, c code, and hardware to run the modification boards in Nevada regulated gaming machines. <br />Assisted in the software and hardware development, installation, maintainance, and QA/testing. <br />Trained and supported customers at the Palms and various other Casinos. Communicated with the Nevada State Gaming Board and GLI for gaming device testing.
 - title: Lead Programmer
   start: 2008
   end: 2010
   employer: General Operations
   description: ➢ Productively multitasked between managing, programming, and troubleshooting for 200+ clients on over 10,000+ domain names. <br />Regularly made improvements to the company’s approach, consistency, re-usability, documentation style, and development methodologies. <br />Managed team of 6 remote and in-house developers pushing out a site a day.
 - title: IT Director
   start: 2004
   end: 2008
   employer: RE/MAX Towers
   description: Created and managed the company’s PHP sites by adding and updating SEO and compiling to the strict HTML W3C markup standards and got them ranking high quickly in google. <br />Built custom Java applications that interfaced with remote databases to update REALTORS on their properties and transactions. <br />Self-managed multi-office VPNs, Linux, & Microsoft Exchange servers used for sensitive transaction data.

#Education is required
education:
 - level: Assocites of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/learning-neural-networks
 - robhinds/akka-http-rest-api-sample
 - robhinds/twitter-sentiment-analysis
 - robhinds/spring-reactor-twitter
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/food2vec
 - robhinds/SpringMongoIntegrationExample
 - robhinds/SpringNeo4JWebApp
 - robhinds/AndroidChuckQuiz
 - robhinds/AndroidRssReader

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/258813/rhinds
   flairimageurl: http://stackoverflow.com/users/flair/258813.png

#Mobile apps section is optional
apps:
 - name: Chuck the Quiz
   platform: Android
   url: https://play.google.com/store/apps/details?id=com.tmm.android.chuck&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS50bW0uYW5kcm9pZC5jaHVjayJd
   description: A basic early Android app (open sourced)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>). <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
